version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on 'date'
      - npm run build
  post_build:
    commands:
      # copy the contents of /build to S3
      - aws s3 cp --recursive --acl public-read ./build s3://semo-react-cf-s3/
      # set the cache-control headers for index.html to prevent
      # browser caching
      - aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build/index.html s3://semo-react-cf-s3/
      # Invalidate the CloudFront cache
      - aws cloudfront  create-invalidation --distribution-id E2RG6S9MC9RD3S --paths /*
artifacts:
  files:
    - "build/*"
    - "build/**/*"